name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form (8-10 min) il venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 0) Seleziona Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 1) Clona il repo
    - uses: actions/checkout@v4

    # 2) Installa dipendenze
    - name: Install system & Python deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget
        python -m pip install --upgrade pip
        # installa i requirements nello stesso site-packages di Python 3.11
        PIP_BREAK_SYSTEM_PACKAGES=1 python -m pip install -r requirements.txt
        # installa Piper TTS (senza dipendenze extra)
        PIP_BREAK_SYSTEM_PACKAGES=1 python -m pip install piper-tts==1.2.0 --no-deps

    # 3) Avvia la pipeline
    - name: Run pipeline
      env:
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        if [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi
        python scripts/pipeline.py --mode $MODE
