name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form (8-10 min) ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 0) Setup Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 1) Checkout del repository
    - uses: actions/checkout@v4

    # 2) Installa ffmpeg + wget e poi tutte le dipendenze Python
    - name: Install system & Python deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget
        python3 -m pip install --upgrade pip
        python3 -m pip install --user -r requirements.txt
        python3 -m pip install --user piper-tts==1.2.0 --no-deps

    # 3) Avvia la pipeline con python3 -E (carica anche ~/.local)
    - name: Run pipeline
      env:
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        if [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi
        python3 -E scripts/pipeline.py --mode $MODE
