name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form (8-10 min) ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout del codice
    - uses: actions/checkout@v4

    # 2) Setup Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3) Unico step: crea venv, installa dipendenze e lancia pipeline
    - name: Setup venv & run pipeline
      shell: bash
      env:
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        # 3.1) Dipendenze di sistema
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget

        # 3.2) Venv Python
        python -m venv .venv
        source .venv/bin/activate

        # 3.3) Pip e librerie
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install piper-tts==1.2.0 --no-deps

        # 3.4) Determina modalità da cron
        if [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi

        # 3.5) Esegui la pipeline
        python scripts/pipeline.py --mode $MODE
