name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form (8-10 min) ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout del codice
    - uses: actions/checkout@v4

    # 2) Installa ffmpeg + wget
    - name: Install system deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget

    # 3) Setup Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 4) Installa tutte le librerie in una cartella locale
    - name: Install Python deps locally
      run: |
        python -m pip install --upgrade pip
        # crea la cartella dei deps
        mkdir -p python-deps
        # installa requirements dentro python-deps
        python -m pip install --target=python-deps -r requirements.txt
        # installa Piper TTS senza dipendenze extra
        python -m pip install --target=python-deps piper-tts==1.2.0 --no-deps

    # 5) Esegue la pipeline usando python-deps via PYTHONPATH
    - name: Run pipeline
      env:
        PYTHONPATH: ${{ github.workspace }}/python-deps
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        if [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi
        python scripts/pipeline.py --mode $MODE
