name: YouTube Bot

on:
  schedule:
    # Shorts ogni ora
    - cron: '0 * * * *'
    # Long-form ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:
    inputs:
      mode:
        description: 'short o long'
        required: false
        default: 'short'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system & Python dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget        # ← installa ffmpeg e wget
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install piper-tts==1.2.0 --no-deps

    - name: Run pipeline
      env:
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        # Determina la modalità (dispatch vs schedule)
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          MODE="${{ github.event.inputs.mode }}"
        elif [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi
        python scripts/pipeline.py --mode "$MODE"
