name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form (8-10 min) ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout
    - uses: actions/checkout@v4

    # 2) Setup Python (installa 3.11 e mette `python` in PATH)
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3) Installa dipendenze di sistema e Python
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget
        python -m pip install --upgrade pip
        # installa tutte le librerie Python nel venv di setup-python
        python -m pip install -r requirements.txt
        # installa Piper TTS (skip delle dipendenze mancanti)
        python -m pip install piper-tts==1.2.0 --no-deps

    # 4) Esegue la pipeline
    - name: Run pipeline
      env:
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        if [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi
        python scripts/pipeline.py --mode $MODE
