name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form (8-10 min) ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Clona il repository
    - uses: actions/checkout@v4

    # 2) Setup Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3) Installa dipendenze di sistema e Python in site-packages di sistema
    - name: Install system & Python deps
      run: |
        sudo apt-get update -y
        # Pip system-wide
        sudo apt-get install -y ffmpeg wget python3-pip
        # Ora pip punta al pip di sistema
        sudo python3 -m pip install --upgrade pip setuptools wheel
        # Installa le librerie nel site-packages di sistema
        sudo python3 -m pip install -r requirements.txt
        # Piper TTS (senza dipendenze extra)
        sudo python3 -m pip install piper-tts==1.2.0 --no-deps

    # 4) Esegue la pipeline
    - name: Run pipeline
      env:
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        if [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi
        python3 scripts/pipeline.py --mode $MODE
