name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:
    inputs:
      mode:
        description: 'short o long'
        required: false
        default: 'short'
        type: choice
        options:
          - short
          - long

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout
    - uses: actions/checkout@v4

    # 2) Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3) System deps + pip
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install onnxruntime
        python -m pip install piper-tts==1.2.0 --no-deps

    # 4) Run pipeline
    - name: Run pipeline
      env:
        PYTHONPATH: ${{ github.workspace }}/python-deps
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
          MODE=${{ github.event.inputs.mode }}
        else
          # scheduled run
          MODE=short
        fi
        python scripts/pipeline.py --mode $MODE
