name: YouTube Bot

on:
  schedule:
    # Short ogni ora
    - cron: '0 * * * *'
    # Long-form (8-10 min) ogni venerdì alle 18:00 CET
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout
    - uses: actions/checkout@v4

    # 2) Setup Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3) Installa dipendenze di sistema
    - name: Install system deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg wget

    # 4) Crea ed entra in un virtualenv, installa tutto lì
    - name: Setup venv & install Python deps
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install piper-tts==1.2.0 --no-deps

    # 5) Run pipeline usando il venv
    - name: Run pipeline
      shell: bash
      env:
        PEXELS_KEY:   ${{ secrets.PEXELS_KEY }}
        HF_TOKEN:     ${{ secrets.HF_TOKEN }}
        GOOGLE_OAUTH: ${{ secrets.GOOGLE_OAUTH }}
      run: |
        source venv/bin/activate
        if [[ "${{ github.event.schedule }}" == '0 * * * *' ]]; then
          MODE=short
        else
          MODE=long
        fi
        python scripts/pipeline.py --mode $MODE
